#!/usr/bin/php
<?php

// Disable iphone alerts
$debug = true;

require_once('include/bootstrap.php');

/*
********************************************************************************
*
*			    Main Code Block
*
********************************************************************************
*/

// Initialize iPhone locator
$i = new iPhoneCommunicator;

// Start main loop, read Arduino stream and alert when movement occurs
# /dev/cu.usbmodem5d21

$handle = fopen('/dev/cu.usbmodem5d21', 'r');
echo "Pausing to wait for Arduino boot.\n";
sleep(4);
echo "System ready.\n";
if ($handle)
{

	while (true)
	{
		$message = '';
		list($item, $state, $num) = preg_split('/_/', trim(fgets($handle, 20)));
		switch ($state)
		{
			case 'OPEN':
				alert("Switch {$num} loop interrupted");
			break;
			case 'CLOSED':
				alert("Switch {$num} restored to closed state");
			break;
		}
	}
}

function alert($message)
{
	global $i, $debug;
	echo date('r') . ": $message. ";
	if (! isset($debug) || ! $debug)
	{
		echo "Sending iPhone status update.\n";
		$i->send_alert("Alert: " . $message, "Arduino Status Update");
	} else {
		echo "Debug mode, no alert sent.\n";
	}
}
